// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Minter represents the minting state.
type Minter struct {
	// current annual inflation rate
	Inflation github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=inflation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"inflation"`
	// current annual expected provisions
	AnnualProvisions     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=annual_provisions,json=annualProvisions,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"annual_provisions" yaml:"annual_provisions"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Minter) Reset()         { *m = Minter{} }
func (m *Minter) String() string { return proto.CompactTextString(m) }
func (*Minter) ProtoMessage()    {}
func (*Minter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}
func (m *Minter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Minter.Unmarshal(m, b)
}
func (m *Minter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Minter.Marshal(b, m, deterministic)
}
func (m *Minter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Minter.Merge(m, src)
}
func (m *Minter) XXX_Size() int {
	return xxx_messageInfo_Minter.Size(m)
}
func (m *Minter) XXX_DiscardUnknown() {
	xxx_messageInfo_Minter.DiscardUnknown(m)
}

var xxx_messageInfo_Minter proto.InternalMessageInfo

type MinterCustom struct {
	NextBlockToUpdate uint64 `protobuf:"varint,1,opt,name=next_block_to_update,json=nextBlockToUpdate,proto3" json:"next_block_to_update,omitempty" yaml:"next_block_to_update"`
	// current annual expected provisions
	AnnualProvisions     github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,2,opt,name=annual_provisions,json=annualProvisions,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"annual_provisions" yaml:"annual_provisions"`
	MintedPerBlock       github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,opt,name=minted_per_block,json=mintedPerBlock,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coins" json:"minted_per_block" yaml:"minted_per_block"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *MinterCustom) Reset()         { *m = MinterCustom{} }
func (m *MinterCustom) String() string { return proto.CompactTextString(m) }
func (*MinterCustom) ProtoMessage()    {}
func (*MinterCustom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}
func (m *MinterCustom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinterCustom.Unmarshal(m, b)
}
func (m *MinterCustom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinterCustom.Marshal(b, m, deterministic)
}
func (m *MinterCustom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinterCustom.Merge(m, src)
}
func (m *MinterCustom) XXX_Size() int {
	return xxx_messageInfo_MinterCustom.Size(m)
}
func (m *MinterCustom) XXX_DiscardUnknown() {
	xxx_messageInfo_MinterCustom.DiscardUnknown(m)
}

var xxx_messageInfo_MinterCustom proto.InternalMessageInfo

func (m *MinterCustom) GetNextBlockToUpdate() uint64 {
	if m != nil {
		return m.NextBlockToUpdate
	}
	return 0
}

// mint parameters
type Params struct {
	// type of coin to mint
	MintDenom string `protobuf:"bytes,1,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	// maximum annual change in inflation rate
	InflationRateChange github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=inflation_rate_change,json=inflationRateChange,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"inflation_rate_change" yaml:"inflation_rate_change"`
	// maximum inflation rate
	// string inflation_max = 3 [
	//   (gogoproto.moretags)   = "yaml:\"inflation_max\"",
	//   (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
	//   (gogoproto.nullable)   = false
	// ];
	// // minimum inflation rate
	// string inflation_min = 4 [
	//   (gogoproto.moretags)   = "yaml:\"inflation_min\"",
	//   (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
	//   (gogoproto.nullable)   = false
	// ];
	// // goal of percent bonded atoms
	// string goal_bonded = 5 [
	//   (gogoproto.moretags)   = "yaml:\"goal_bonded\"",
	//   (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
	//   (gogoproto.nullable)   = false
	// ];
	// expected blocks per year
	BlocksPerYear        uint64   `protobuf:"varint,3,opt,name=blocks_per_year,json=blocksPerYear,proto3" json:"blocks_per_year,omitempty" yaml:"blocks_per_year"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *Params) GetBlocksPerYear() uint64 {
	if m != nil {
		return m.BlocksPerYear
	}
	return 0
}

func init() {
	proto.RegisterType((*Minter)(nil), "cosmos_sdk.x.mint.v1.Minter")
	proto.RegisterType((*MinterCustom)(nil), "cosmos_sdk.x.mint.v1.MinterCustom")
	proto.RegisterType((*Params)(nil), "cosmos_sdk.x.mint.v1.Params")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xbf, 0x6f, 0xd4, 0x30,
	0x14, 0xc7, 0x9b, 0x72, 0x1c, 0x3a, 0xf3, 0xab, 0x35, 0x07, 0x44, 0x05, 0x64, 0xe4, 0x01, 0x75,
	0x21, 0x27, 0xc4, 0xd6, 0x31, 0xd7, 0x89, 0x5f, 0x8a, 0x2c, 0x18, 0x60, 0xb1, 0x7c, 0x89, 0x49,
	0xad, 0x4b, 0xfc, 0x22, 0xdb, 0x29, 0xbd, 0x95, 0xbf, 0x82, 0x91, 0x3f, 0x87, 0x0d, 0x66, 0x86,
	0xfc, 0x11, 0x19, 0x98, 0x51, 0xec, 0x53, 0x2b, 0x95, 0x1b, 0xb8, 0xa9, 0x53, 0xa2, 0x4f, 0x9e,
	0x3e, 0xef, 0x7d, 0x5f, 0x6c, 0x74, 0xd3, 0xad, 0x1a, 0x69, 0x93, 0xc6, 0x80, 0x03, 0x3c, 0xcd,
	0xc1, 0xd6, 0x60, 0xb9, 0x2d, 0x96, 0xc9, 0x59, 0x52, 0x2b, 0xed, 0x92, 0xd3, 0x17, 0x07, 0xd3,
	0x12, 0x4a, 0xf0, 0x05, 0xb3, 0xe1, 0x2d, 0xd4, 0xd2, 0x9f, 0x11, 0x1a, 0xbf, 0x55, 0xda, 0x49,
	0x83, 0xdf, 0xa0, 0x89, 0xd2, 0x9f, 0x2b, 0xe1, 0x14, 0xe8, 0x38, 0x7a, 0x1a, 0x1d, 0x4e, 0xd2,
	0xe4, 0x47, 0x47, 0x76, 0x7e, 0x77, 0xe4, 0x59, 0xa9, 0xdc, 0x49, 0xbb, 0x48, 0x72, 0xa8, 0x67,
	0x41, 0xbe, 0x7e, 0x3c, 0xb7, 0xc5, 0x72, 0x16, 0x7a, 0x1f, 0xcb, 0x9c, 0x5d, 0x08, 0xf0, 0x17,
	0xb4, 0x2f, 0xb4, 0x6e, 0x45, 0xc5, 0x1b, 0x03, 0xa7, 0xca, 0x2a, 0xd0, 0x36, 0xde, 0xf5, 0xd6,
	0x57, 0xdb, 0x59, 0xfb, 0x8e, 0xc4, 0x2b, 0x51, 0x57, 0x47, 0xf4, 0x1f, 0x21, 0x65, 0x7b, 0x81,
	0x65, 0x17, 0xe8, 0xd7, 0x2e, 0xba, 0x15, 0x12, 0xcd, 0x5b, 0xeb, 0xa0, 0xc6, 0x19, 0x9a, 0x6a,
	0x79, 0xe6, 0xf8, 0xa2, 0x82, 0x7c, 0xc9, 0x1d, 0xf0, 0xb6, 0x29, 0x84, 0x93, 0x3e, 0xe2, 0x28,
	0x25, 0x7d, 0x47, 0x1e, 0x05, 0xfd, 0xa6, 0x2a, 0xca, 0xf6, 0x07, 0x9c, 0x0e, 0xf4, 0x3d, 0x7c,
	0xf0, 0xec, 0xca, 0xb2, 0xe1, 0x16, 0xed, 0x0d, 0xbf, 0x53, 0x16, 0xbc, 0x91, 0x26, 0x8c, 0x1a,
	0x5f, 0xf3, 0x7d, 0x5f, 0xaf, 0xfb, 0x1e, 0xfe, 0x47, 0xdf, 0x39, 0x28, 0x6d, 0xfb, 0x8e, 0x3c,
	0x0c, 0x9d, 0x2f, 0x1b, 0x29, 0xbb, 0x13, 0x50, 0x26, 0x8d, 0xcf, 0x4d, 0xff, 0x44, 0x68, 0x9c,
	0x09, 0x23, 0x6a, 0x8b, 0x9f, 0x20, 0x34, 0x7c, 0xe4, 0x85, 0xd4, 0x50, 0x87, 0x53, 0xc2, 0x26,
	0x03, 0x39, 0x1e, 0x00, 0xfe, 0x1a, 0xa1, 0xfb, 0xe7, 0x67, 0x80, 0x1b, 0xe1, 0x24, 0xcf, 0x4f,
	0x84, 0x2e, 0xe5, 0x7a, 0x3d, 0xef, 0xb6, 0x5e, 0xcf, 0xe3, 0x30, 0xe4, 0x46, 0x29, 0x65, 0xf7,
	0xce, 0x39, 0x13, 0x4e, 0xce, 0x3d, 0xc5, 0x29, 0xba, 0xeb, 0x83, 0x58, 0x9f, 0x69, 0x25, 0x85,
	0xf1, 0x4b, 0x1a, 0xa5, 0x07, 0x7d, 0x47, 0x1e, 0x04, 0xdf, 0xa5, 0x02, 0xca, 0x6e, 0x07, 0x92,
	0x49, 0xf3, 0x51, 0x0a, 0x73, 0x34, 0xfa, 0xf6, 0x9d, 0xec, 0xa4, 0x37, 0x3e, 0x5d, 0xf7, 0xb3,
	0x2c, 0xc6, 0xfe, 0xb6, 0xbc, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x11, 0xea, 0x13, 0x68,
	0x03, 0x00, 0x00,
}
